CodingCab/ShipTown

readme.md
=> change clone url

app/Modules/Reports/src/Models/Report.php, resources/views/report-default.blade.php
=> add sort links to inventory report table headers

database/seeders/DatabaseSeeder.php, database/seeders/Demo/CollectionOrdersSeeder.php, database/seeders/Demo/PaidOrdersSeeder.php, database/seeders/Demo/TestOrdersSeeder.php
fixing issue where seeders would not finish because of duplicated product_sku in products table
=> Products seeders fix

app/Http/Controllers/Api/PicklistController.php, app/Http/Resources/OrderPicklistResource.php, package-lock.json, package.json
return 'order_product_ids', add 'order_ids' for accurate order count
=> Picklist controller bug

app/Modules/ActiveOrdersInventoryReservations/src/Listeners/ConfigurationUpdatedEventListener.php, app/Modules/ActiveOrdersInventoryReservations/src/Listeners/OrderProductCreatedEventListener.php, tests/Feature/Modules/ActiveOrdersInventoryReservations/ConfigurationChangedTest.php
=> fix issue with active order reservations whe product alias is used

app/Http/Controllers/Api/HeartbeatsController.php, app/Http/Resources/HeartbeatResources.php, app/Jobs/DispatchEveryDayEventJob.php, app/Jobs/DispatchEveryFiveMinutesEventJob.php, app/Jobs/DispatchEveryHourEventJobs.php, app/Jobs/DispatchEveryMinuteEventJob.php, app/Jobs/DispatchEveryMonthEventJob.php, app/Jobs/DispatchEveryTenMinutesEventJob.php, app/Jobs/DispatchEveryWeekEventJob.php, app/Models/Heartbeat.php, database/migrations/2024_03_22_072347_add_auto_heal_job_class_column_to_heartbeats_table.php, tests/Feature/Api/Heartbeats/IndexTest.php
=> Auto heal to heartbeats 289

database/migrations/2019_10_16_000000_core_v1.php
=> add index directly and remove nullable false

app/Models/Order.php, app/Modules/Api2cart/src/Jobs/ImportShippingAddressJob.php, app/Modules/Api2cart/src/Jobs/ProcessImportedOrdersJob.php, app/Modules/Api2cart/src/Models/Api2cartOrderImports.php, app/Services/OrderService.php, tests/Unit/Modules/Api2cart/Jobs/ProcessImportedRecordJobTest.php, tests/Unit/Services/OrderServiceTest.php
=> Import billing address api2cart 328

app/Modules/Reports/src/Models/Report.php, public/css/app.css
=> report fixed

app/Http/Resources/ProductResource.php, app/Models/Product.php, app/Modules/Reports/src/Models/InventoryReport.php, database/migrations/2024_04_17_133738_add_suppier_column_to_products_table.php
=> add supplier column to products table

app/Modules/Automations/config/automations.php, app/Modules/Automations/src/Conditions/Order/ShippingMethodNameInCondition.php
=> add shipping method in order automations

public/css/app.css, resources/js/app.js, resources/js/components/PointOfSalePage.vue, resources/views/tools/point-of-sale.blade.php, routes/web.php, tests/Browser/Routes/Tools/PointOfSalePageTest.php, tests/Feature/Tools/PointOfSale/IndexTest.php
=> Epos pass tests 399

app/Console/Commands/AppInstall.php
=> first draft install automations on app:install

app/Http/Controllers/Api/TransactionController.php, package-lock.json, public/css/app.css, resources/js/components/PointOfSalePage.vue, resources/js/mixins/api.vue, routes/api.php, tests/Feature/Api/Transactions/Transaction/UpdateTest.php
=> Scan real products

app/Http/Controllers/Api/PrintJobController.php, app/Http/Controllers/Api/TransactionController.php, app/Http/Requests/PrintJob/StoreRequest.php, resources/js/components/PointOfSalePage.vue, resources/js/mixins/api.vue, routes/api.php, tests/Feature/Api/PrintJobs/StoreTest.php, tests/Feature/Api/Transactions/StoreTest.php, tests/Feature/Api/Transactions/Transaction/UpdateTest.php
=> Print receipt

app/Modules/Reports/src/Models/InventoryReport.php
=> add inventory reservations to inventory report

app/Modules/Reports/src/Models/InventoryReport.php, database/migrations/2024_09_26_223414_add_indexes_to_inventory_table.php
=> Add sale statistics to inventory report

resources/js/components/SharedComponents/InventoryMovementCard.vue
=> Link to inventory movements report

app/Http/Controllers/Api/OrderPaymentController.php, app/Http/Resources/OrderPaymentResource.php, app/Http/Resources/OrderResource.php, app/Models/Order.php, app/Models/OrderPayment.php, app/Modules/Api2cart/src/Jobs/ProcessImportedOrdersJob.php, app/Modules/Api2cart/src/Models/Api2cartOrderImports.php, app/Services/OrderService.php, database/factories/OrderPaymentFactory.php, database/migrations/2024_09_27_152840_create_order_payments_table.php, database/migrations/2024_09_27_152840_create_orders_payments_table.php, resources/js/components/Orders/OrderCard.vue, resources/js/mixins/api.vue, routes/api.php, tests/Feature/Api/Order/Payments/IndexTest.php, tests/Unit/Modules/Api2cart/Jobs/ProcessImportedRecordJobTest.php, tests/Unit/Services/OrderServiceTest.php
=> Add order payments data to order

resources/js/components/Reports/Report.vue, resources/js/components/Reports/ReportOrder.vue
=> Memorize report
